const Map<String, String> english = {
  'skip': 'Skip',
  'onboardingTitle1': 'Healthy cooking recipes',
  'onboardingSubTitle1': 'Explore a world of healthy recipes designed just for you! Whether you\'re looking for weight loss, a balanced diet, or quick and healthy meals, we have everything you need to start your journey to a better life.',
  'onboardingTitle2': 'Health and pleasure in every bite',
  'onboardingSubTitle2': 'There\'s no need to sacrifice taste for health! With our app, you\'ll find nutritious, quick-to-prepare recipes that help you maintain your diet while enjoying delicious food.',
  'onboardingTitle3': 'Cook smart, eat healthy',
  'onboardingSubTitle3': 'With thousands of healthy and easy recipes, you can now prepare delicious dishes without worrying about your health. Discover cooking tips, simple steps, and precise ingredients for every meal!',
  'success':'Success',
  'error':'Error',
  'warning':'Warning',
  'close':'Close',
  'version': 'Version',
  'somethingWentWrong':'Something Went Wrong',
  'about': 'About',
  'language': 'Language',
  'darkMode': 'Dark Mode',
  'english': 'English',
  'general': 'General',
  'arabic': 'Arabic',
  'add': 'Add',
  'cancel': 'Cancel',
  'home':'Home',
  'categories': 'Categories',
  'favorite':'Favorite',
  'settings':'Settings',
  'homeTitle':'Hello',
  'homeSubTitle':'Find your favorite recipe for food',
  'foodMenu':'Food Menu',
  'foodName':'Healthy Meals',
  'components':'Components',
  'timeFood':'Meal Preparation Time',
  'cookingMethod':'Cooking Method',
  'time':'Time',
  'noData': 'There are no recipes currently available.',
  'back': 'Back',
  'messageAboutUs': 'We are a team of passionate food lovers, committed to bringing you the best healthy recipes.',
};