name: wasfati
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Utility Package
  dio: ^5.8.0+1
  intl: ^0.20.2
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.5
  smooth_page_indicator: ^1.2.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.7.2
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/on_boarding/
    - assets/images/banner/
    - assets/images/error/
    - assets/logos/